### ISSUE TITLE
Bluetooth doesn't work

### ISSUE THREAD

**Issue by Espionage724** [AsteroidOS/meta-tetra-hybris#1]
Seems like there was a bit of work done for the SW3. Just wondering, but what else is needed?

**Comment by FlorentRevest** [comment]
It's been a while I haven't worked on the issue but as far as I can remember Bluetooth support on SW3 is blocked because of a problem in the kernel driver that handles the UART communication to the BT Chip. A similar problem prevented battery life on QCOM devices and has been solved by hacking around "bluedroid" for example in https://github.com/AsteroidOS/meta-dory-hybris/blob/master/recipes-kernel/linux/linux-dory/0002-bluesleep-Use-kernel-s-HCI-events-instead-of-proc-bl.patch but the driver written by Broadcom is a bit different. You may find more info in the IRC logs

**Comment by fergy** [comment]
...also I think that We need here this: https://github.com/shr-distribution/meta-smartphone/blob/master/meta-android/recipes-bsp/firmware/bcm4330-firmware_4.1.2.bb

**Comment by FlorentRevest** [comment]
@fergy : the correct firmware is already provided by "android-tetra" https://github.com/AsteroidOS/meta-tetra-hybris/blob/master/recipes-android/android/android_tetra-lp.bb We definitely don't need this

**Comment by fergy** [comment]
@FlorentRevest Ok. I will make debug of problem but Kernel is 100% right and no issue neather LP or MM with working BT on Android so We need to check other solutions.

**Comment by FlorentRevest** [comment]
I insist on that the kernel is the issue on Asteroid. You need to change the code of the BT driver which currently makes the assumption that you are running an android userspace.
Updating the kernel is *not* enough to automatically solve our problem.

**Comment by fergy** [comment]
Ok. As I say,  will make deeper debug and compare (probably) not compatible code with something what work. Please let Me know which device work.
Thx

**Comment by FlorentRevest** [comment]
dory or bass have working BT but while they use pretty much the same Broadcom chip, firmware and flashing tool, the QCOM kernel drivers (bluesleep for example) work differently so it's hard to compare.

**Comment by fergy** [comment]
Great. Thank You. Will inspect this issue.

**Comment by nicofossa** [comment]
I don't know if it may help, but I did some test some month ago because it wasn't possible to upload the firmware to the chip. I'd achieved that by pulling up a GPIO (I think that could be the sleep pin), then I could upload the firmware (but no bluetooth working) using brcm-patchram-plus.
If it can help you I may try to look for more information on my old build machine

**Comment by Technohacker** [comment]
Bluetooth works now? :D

**Comment by FlorentRevest** [comment]
Bluetooth has indeed been tested by myself and reported to work by other community members.

**Comment by Technohacker** [comment]
Good to hear. Am making a build atm, thanks for the effort! :D
